export const BaseUrl = `http://127.0.0.1:8000/api/`;
export const LOG_IN='/login'
export const ADMIN =`admin`
export const ME =`/me`
export const Products =`products`
export const APOINNTS =`/appointments`
export const STATS =`/stats`
export const DASHBOARD =`/dashboard`
export const ANNONCEMNTS =`/announcements`
export const DOCTORS = `/doctors`
export const VERIFY =`/verify`
export const PATIENTS =`/patients`
export  const Roles = `/roles`
export const Clincs = `/clinics`
export const TOGGIL =`/toggle-status`
export const PIRRIMISSION =`/permissions`
export const LIST =`/list`
